version: "3.3"

services:

  filestorage:
    image: minio/minio:RELEASE.2022-10-20T00-55-09Z
    volumes:
      - ./data:/data
    ports:
      - 9090:9090
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: secretpassword
    command: server /data --console-address ':9090'

  proxy:
    image: nginx:1.23.2-alpine
    ports:
      - 80:80
    volumes:
      - ./reverse_proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf:ro