version: "3.3"

services:
  backend:
    image: async-backend
    build:
      context: backend
    volumes:
      - './backend:/usr/src/app'
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - db
    environment:
      ROOT_PATH: '/api/v1'
      SQLALCHEMY_DATABASE_URL: 'postgresql://postgres:postgres@db:5432/postgres'

  backend_migrations:
    image: flyway/flyway
    volumes:
      - ./backend/migrations:/flyway/sql
    networks:
      - db
    depends_on:
      - db
    command: -url=jdbc:postgresql://db:5432/postgres -schemas=public -user=postgres -password=postgres -connectRetries=60 migrate

  queue:
    image: apachepulsar/pulsar-standalone
    environment:
      - LOG4J_FORMAT_MSG_NO_LOOKUPS: 'true'
    ports:
      - 80:80
      - 8080:8080
      - 6650:6650
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf

  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - db
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
  pulsardata:
  pulsarconf:

networks:
  db:
