appID: test-asyncwrapper
wrapperClass: org.n.riesgos.asyncwrapper.dummy.ShakygroundWrapper
#pulsar properties
pulsar:
    pulsarURL : pulsar://localhost:6650
    orderTopic: new-order
    inputTopics :
        - input-topic1
        - input-topic2
        - input-topic3
    outputTopic : output-topic
    failureTopic: failure-topic
#wps properties
wps:
    wpsURL : https://rz-vm140.gfz-potsdam.de/wps/WebProcessingService
    wpsVersion : 2.0.0
    process : org.n52.wps.server.algorithm.test.EchoProcess
    # Currently we support string values here.
    # In case of '52nwps' we have some different handling for setting the
    # reference parameter schemas & encoding.
    dialect: 52nwps
    outputs:
        -
            identifier: complexOutput
            mimeType: text/xml
    retryConfiguration:
        maxRetries: 10
        backoffMillis: 1000
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
filestorage:
    endpoint: http://138.246.225.182
    user: user
    password: password
    bucketName: riesgosfiles
    access: http://138.246.225.182/api/v1/files/
    retryConfiguration:
        maxRetries: 10
        backoffMillis: 1000

